Repository sravan1946/sravan-cogs, pull requests merged in 2022-10, with the labels that each got.

#6 adding participants
  gtn/Guessthenumber.py
Labels: hacktoberfest-accepted

#8 fixed timeout
  timeout/timeout.py
Labels: bug, hacktoberfest-accepted

#10 Update perform.py and some utils
  perform/perform.py
  perform/utils.py
Labels: enhancement, hacktoberfest-accepted

#12 Make User Optional for some cases in send_embed()
  perform/utils.py
Labels: bug, hacktoberfest-accepted

#16 minor enhancements
  dps/dps.py
Labels: enhancement, hacktoberfest-accepted
